import * as THREE from 'three';
import { ShaderPass } from 'three/examples/jsm/postprocessing/ShaderPass.js';

/**
 * THE SIGNATURE EFFECT — ordered dither / halftone screen (spec 6.6).
 *
 * The dot grid is visible across every reference frame, including the background,
 * so it is applied to the composited image rather than to the body.
 *
 * THE ONE THING THAT MATTERS: the grid is sampled in DEVICE pixels.
 *
 *     vec2 cell = floor(gl_FragCoord.xy / uDotSize);
 *
 * `gl_FragCoord` is already in the render target's pixels, so as long as the
 * composer runs at native DPR this is device-pixel-exact. If you dither at CSS
 * resolution and let the browser upscale, or if you dither before any resampling
 * pass, the pattern turns to mush. That is the single most common way to get this
 * effect wrong, and it is why this is the last pass before the vignette.
 *
 * This pass also carries the tone map and colour grade, because doing them in one
 * pass avoids a full-screen round trip and because the dither MUST come after tone
 * mapping — dithering a linear buffer and then tone mapping it redistributes the
 * pattern non-uniformly across the tonal range and the grid stops looking regular.
 */

const BAYER_8 = /* glsl */ `
// 8x8 Bayer matrix, normalised to [0,1). Generated by the recursive
// M_{2n} = [[4M_n, 4M_n+2],[4M_n+3, 4M_n+1]] construction and written out flat so
// the shader needs no array indexing tricks on older drivers.
float bayer8(vec2 cell) {
  int x = int(mod(cell.x, 8.0));
  int y = int(mod(cell.y, 8.0));
  int i = y * 8 + x;
  float v = 0.0;
  if      (i ==  0) v =  0.0;  else if (i ==  1) v = 32.0; else if (i ==  2) v =  8.0; else if (i ==  3) v = 40.0;
  else if (i ==  4) v =  2.0;  else if (i ==  5) v = 34.0; else if (i ==  6) v = 10.0; else if (i ==  7) v = 42.0;
  else if (i ==  8) v = 48.0;  else if (i ==  9) v = 16.0; else if (i == 10) v = 56.0; else if (i == 11) v = 24.0;
  else if (i == 12) v = 50.0;  else if (i == 13) v = 18.0; else if (i == 14) v = 58.0; else if (i == 15) v = 26.0;
  else if (i == 16) v = 12.0;  else if (i == 17) v = 44.0; else if (i == 18) v =  4.0; else if (i == 19) v = 36.0;
  else if (i == 20) v = 14.0;  else if (i == 21) v = 46.0; else if (i == 22) v =  6.0; else if (i == 23) v = 38.0;
  else if (i == 24) v = 60.0;  else if (i == 25) v = 28.0; else if (i == 26) v = 52.0; else if (i == 27) v = 20.0;
  else if (i == 28) v = 62.0;  else if (i == 29) v = 30.0; else if (i == 30) v = 54.0; else if (i == 31) v = 22.0;
  else if (i == 32) v =  3.0;  else if (i == 33) v = 35.0; else if (i == 34) v = 11.0; else if (i == 35) v = 43.0;
  else if (i == 36) v =  1.0;  else if (i == 37) v = 33.0; else if (i == 38) v =  9.0; else if (i == 39) v = 41.0;
  else if (i == 40) v = 51.0;  else if (i == 41) v = 19.0; else if (i == 42) v = 59.0; else if (i == 43) v = 27.0;
  else if (i == 44) v = 49.0;  else if (i == 45) v = 17.0; else if (i == 46) v = 57.0; else if (i == 47) v = 25.0;
  else if (i == 48) v = 15.0;  else if (i == 49) v = 47.0; else if (i == 50) v =  7.0; else if (i == 51) v = 39.0;
  else if (i == 52) v = 13.0;  else if (i == 53) v = 45.0; else if (i == 54) v =  5.0; else if (i == 55) v = 37.0;
  else if (i == 56) v = 63.0;  else if (i == 57) v = 31.0; else if (i == 58) v = 55.0; else if (i == 59) v = 23.0;
  else if (i == 60) v = 61.0;  else if (i == 61) v = 29.0; else if (i == 62) v = 53.0; else v = 21.0;
  return v / 64.0;
}
`;

export const DITHER_FRAG = /* glsl */ `
uniform sampler2D tDiffuse;
uniform float uDotSize;
uniform float uStrength;
uniform float uVignette;
uniform float uWarmth;
uniform float uExposure;
uniform vec2  uResolution;
varying vec2 vUv;

${BAYER_8}

/*
 * Highlight roll-off, NOT a full filmic curve.
 *
 * A textbook ACES curve is the wrong tool for this image and it took a screenshot
 * to see why. ACES compresses the highlights hard, and this entire composition
 * lives in the highlights: the background is 0.86 linear and the tissue only a
 * little below it. Running it through ACES collapsed a 13 % transmittance
 * difference into five 8-bit levels, and the body nearly vanished.
 *
 * What is actually needed is an identity below the background level and a smooth
 * roll-off above it, so the additive rim can exceed 1.0 without clipping while the
 * body keeps every bit of its absorption contrast.
 */
vec3 softShoulder(vec3 x) {
  const float KNEE = 0.86;
  vec3 over = max(x - KNEE, vec3(0.0));
  return min(x, vec3(KNEE)) + (1.0 - KNEE) * (over / (over + (1.0 - KNEE)));
}

void main() {
  vec3 color = texture2D(tDiffuse, vUv).rgb * uExposure;

  // --- highlight roll-off --------------------------------------------------
  color = softShoulder(color);

  // --- warm grade ---------------------------------------------------------
  // Push the mid-tones toward the cream, leave the highlights alone so the rim
  // stays neutral white.
  vec3 warm = vec3(1.0 + 0.045 * uWarmth, 1.0 + 0.012 * uWarmth, 1.0 - 0.030 * uWarmth);
  color = mix(color, color * warm, 0.85);

  // --- linear to display --------------------------------------------------
  color = pow(color, vec3(1.0 / 2.2));

  // --- ORDERED DITHER, in device pixels -----------------------------------
  vec2 cell = floor(gl_FragCoord.xy / uDotSize);
  float threshold = bayer8(cell) - 0.5;
  color += threshold * uStrength;

  // --- vignette -----------------------------------------------------------
  vec2 p = vUv - 0.5;
  float r = length(p * vec2(uResolution.x / max(uResolution.y, 1.0), 1.0));
  color *= 1.0 - uVignette * smoothstep(0.35, 1.05, r);

  gl_FragColor = vec4(color, 1.0);
}
`;

export const DITHER_VERT = /* glsl */ `
varying vec2 vUv;
void main() {
  vUv = uv;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`;

export interface DitherOptions {
  dotSize?: number;
  strength?: number;
  vignette?: number;
  warmth?: number;
  exposure?: number;
}

export function createDitherPass(options: DitherOptions = {}): ShaderPass {
  const pass = new ShaderPass({
    name: 'DitherGrade',
    uniforms: {
      tDiffuse: { value: null },
      uDotSize: { value: options.dotSize ?? 3.0 },
      uStrength: { value: options.strength ?? 0.12 },
      uVignette: { value: options.vignette ?? 0.1 },
      uWarmth: { value: options.warmth ?? 1.0 },
      uExposure: { value: options.exposure ?? 1.0 },
      uResolution: { value: new THREE.Vector2(1, 1) },
    },
    vertexShader: DITHER_VERT,
    fragmentShader: DITHER_FRAG,
  });
  return pass;
}
