import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { EmitResult } from './emit';
import type { Drug } from '../../src/data/pharma-types';
import physiology from '../../src/data/physiology.json';

/**
 * Writes docs/MISSING_CONSTANTS.md (spec 0.4, 5.6).
 *
 * The rule the whole project hangs on: "A wrong number that looks right is worse
 * than a missing one, because it teaches the user something false with full
 * confidence." This report is the audit trail for every place we chose `null`, and
 * for every value that is derived rather than measured.
 */

export function writeMissingConstants(root: string, result: EmitResult): void {
  const lines: string[] = [];

  lines.push('# MISSING CONSTANTS');
  lines.push('');
  lines.push('> **Generated by `tools/ingest/report.ts`. Do not edit by hand — re-run `npm run ingest`.**');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('Every entry here is a number the engine does not have. A missing constant');
  lines.push('contributes **zero** to the simulation and renders as an em-dash (`—`) in the UI.');
  lines.push('It is never filled in with a plausible-looking value (spec 0.4).');
  lines.push('');

  /* --------------------------------------------------- physiology nulls */
  lines.push('## 1. Physiology constants with no sourced value');
  lines.push('');
  const nullPhys: string[] = [];
  // The constants table holds two shapes: leaf entries with a `value`, and nested
  // maps (transit times, segment lengths) whose leaves are the values. Both can
  // carry nulls, so the walk below handles each explicitly.
  const constants = physiology.constants as unknown as Record<string, Record<string, unknown>>;
  for (const [key, entry] of Object.entries(constants)) {
    if (entry && typeof entry === 'object' && 'value' in entry && entry.value === null) {
      nullPhys.push(`| \`${key}\` | ${String(entry.note ?? '')} |`);
    }
    // Nested constant maps (transit times, segment lengths) can hold nulls too.
    if (entry && typeof entry === 'object' && !('value' in entry)) {
      for (const [k, v] of Object.entries(entry)) {
        if (v === null) nullPhys.push(`| \`${key}.${k}\` | ${String(entry.note ?? '')} |`);
      }
    }
  }
  if (nullPhys.length === 0) {
    lines.push('_None. Every constant in `src/data/physiology.json` carries a sourced value._');
  } else {
    lines.push('| Constant | Why it is null |');
    lines.push('|---|---|');
    lines.push(...nullPhys);
  }
  lines.push('');

  /* ------------------------------------------------------- missing PK */
  lines.push('## 2. Pharmacology fields with no source');
  lines.push('');
  if (result.missing.length === 0) {
    lines.push('_None._');
  } else {
    lines.push('| Drug | Field | Reason |');
    lines.push('|---|---|---|');
    for (const m of result.missing) {
      lines.push(`| \`${m.drugId}\` | \`${m.field}\` | ${m.reason} |`);
    }
  }
  lines.push('');

  /* ------------------------------------------------------ null fields */
  lines.push('## 3. Emitted `null` fields, by drug');
  lines.push('');
  lines.push('A null here is deliberate. The field either does not apply (an electrolyte has no');
  lines.push('volume of distribution) or could not be traced to a source.');
  lines.push('');
  lines.push('| Drug | Null fields |');
  lines.push('|---|---|');
  for (const d of result.drugs) {
    const nulls = nullFieldsOf(d);
    if (nulls.length > 0) lines.push(`| \`${d.id}\` | ${nulls.map((n) => `\`${n}\``).join(', ')} |`);
  }
  lines.push('');

  /* ------------------------------------------------------- derived */
  lines.push('## 4. Derived, not measured');
  lines.push('');
  lines.push('These values are arithmetic on cited quantities, or an inference from a qualitative');
  lines.push('statement in a label. They are as good as the reasoning shown, and no better.');
  lines.push('');
  lines.push('| Drug | Field | How it was derived |');
  lines.push('|---|---|---|');
  for (const d of result.drugs) {
    for (const [field, p] of Object.entries(d.pk.provenance)) {
      if (p.confidence === 'derived' || p.confidence === 'assumed') {
        lines.push(`| \`${d.id}\` | \`${field}\` | ${p.note ?? p.source} |`);
      }
    }
  }
  lines.push('');

  /* --------------------------------------------------------- drift */
  lines.push('## 5. Cross-check drift (curated value vs. the openFDA SPL parse)');
  lines.push('');
  lines.push('The SPL parser reads section 12.3 prose. It is advisory: a disagreement here means');
  lines.push('the parse picked a different number (often a paediatric or hepatic-impairment figure),');
  lines.push('or that the curated value should be revisited. It never overwrites a cited value.');
  lines.push('');
  lines.push('**This list is the one that needs work.** A disagreement nobody has ruled on is');
  lines.push('indistinguishable from one nobody has read. Once it has been ruled on it moves to');
  lines.push('5.1 with its reasoning attached, so this table is expected to be empty.');
  lines.push('');
  if (result.drift.length === 0) {
    lines.push('_No unadjudicated disagreements._');
  } else {
    lines.push('| Drug | Disagreement |');
    lines.push('|---|---|');
    for (const d of result.drift) lines.push(`| \`${d.drugId}\` | ${d.message} |`);
  }
  lines.push('');

  /* ------------------------------------------------------ adjudicated */
  lines.push('### 5.1 Adjudicated disagreements');
  lines.push('');
  lines.push('Each of these has been examined and ruled on in `tools/ingest/drift_adjudication.ts`.');
  lines.push('Nothing here is suppressed: the comparison still runs, the disagreement is still');
  lines.push('printed, and if a curated value changes or the parser starts matching a different');
  lines.push('sentence the ruling stops applying and the row returns to 5 as unexplained.');
  lines.push('');
  lines.push('The pattern is worth noting. In five of the six the curated figure and the parsed');
  lines.push('figure come from **the same document**: a human read the label and took the sentence');
  lines.push('about the drug, while the regex took one about a metabolite, an enantiomer, a');
  lines.push('different drug class, or a different experiment. That is a limit of reading prose');
  lines.push('with a pattern, not evidence that the curated value is wrong.');
  lines.push('');
  if (result.adjudicatedDrift.length === 0) {
    lines.push('_None._');
  } else {
    for (const d of result.adjudicatedDrift) {
      lines.push(`**\`${d.drugId}\`** — ${d.verdict}`);
      lines.push('');
      lines.push(`> ${d.message}`);
      lines.push('');
      lines.push(d.because);
      lines.push('');
    }
  }

  /* ------------------------------------------------- unmapped targets */
  lines.push('## 6. Known binding we do not model');
  lines.push('');
  lines.push('GtoPdb publishes a human affinity for these ligand-target pairs, but the target is');
  lines.push('not in `tools/ingest/receptor_registry.ts`, so the interaction is dropped rather than');
  lines.push('approximated onto a different receptor. This list is the honest answer to "what is');
  lines.push('this drug doing that the simulation cannot show you".');
  lines.push('');
  const byDrug = new Map<string, { target: string; nM: number | null }[]>();
  for (const u of result.unmappedTargets) {
    const list = byDrug.get(u.drugId) ?? [];
    if (!list.some((x) => x.target === u.target)) list.push({ target: u.target, nM: u.nM });
    byDrug.set(u.drugId, list);
  }
  if (byDrug.size === 0) {
    lines.push('_None._');
  } else {
    lines.push('| Drug | Unmodelled targets (tightest first) |');
    lines.push('|---|---|');
    for (const [drugId, list] of byDrug) {
      list.sort((a, b) => (a.nM ?? Infinity) - (b.nM ?? Infinity));
      const shown = list.slice(0, 12).map((x) => `${x.target}${x.nM !== null ? ` (${fmtNm(x.nM)})` : ''}`);
      const extra = list.length > 12 ? ` … and ${list.length - 12} more` : '';
      lines.push(`| \`${drugId}\` | ${shown.join(', ')}${extra} |`);
    }
  }
  lines.push('');

  writeFileSync(join(root, 'docs', 'MISSING_CONSTANTS.md'), lines.join('\n') + '\n', 'utf8');
}

function nullFieldsOf(d: Drug): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(d.pk)) {
    if (k === 'provenance') continue;
    if (v === null) out.push(k);
  }
  return out;
}

function fmtNm(nM: number): string {
  if (nM < 1) return `${(nM * 1000).toFixed(0)} pM`;
  if (nM < 1000) return `${nM.toFixed(1)} nM`;
  return `${(nM / 1000).toFixed(1)} µM`;
}
