import type { Route } from '../bridge/types';

/**
 * LAYER D — pharmacology schema (spec 5.5).
 *
 * These files are GENERATED by tools/ingest/, never hand-typed. Every numeric field
 * carries `{ value, unit, source, sourceUrl, confidence }` or is `null`. A null
 * renders as an em-dash, contributes zero to the engine, and is listed in
 * docs/MISSING_CONSTANTS.md.
 */

export interface Provenance {
  source: string;
  sourceUrl: string;
  confidence: 'measured' | 'derived' | 'assumed';
  note?: string;
}

export type DrugClass =
  | 'catecholamine'
  | 'antiarrhythmic'
  | 'electrolyte'
  | 'fluid'
  | 'opioid'
  | 'sedative'
  | 'anaesthetic'
  | 'stimulant'
  | 'psychedelic'
  | 'antihypertensive'
  | 'other';

export interface PresetDose {
  route: Route;
  amount: number;
  unit: string;
  label: string;
  /** Duration for an infusion preset, minutes. Omitted for bolus routes. */
  durationMin?: number;
}

export interface PkParams {
  /** Central compartment volume, L. */
  V1_L: number | null;
  V2_L: number | null;
  V3_L: number | null;
  /** Elimination and inter-compartmental rate constants, per minute. */
  k10_min: number | null;
  k12_min: number | null;
  k21_min: number | null;
  k13_min: number | null;
  k31_min: number | null;
  /** Fraction of total elimination that is renal. Scales with live GFR. */
  renalFraction: number | null;
  /** Fraction bound to plasma protein. Only the free fraction binds receptors. */
  proteinBound: number | null;
  MW_gmol: number | null;
  /** Octanol-water partition coefficient. Drives blood-brain barrier access. */
  logP: number | null;
  /** 0..1 access to central receptors, derived from logP. */
  bbbPenetration: number | null;
  /** Oral/IM absorption. */
  ka_min: number | null;
  lagTime_min: number | null;
  bioavailability: number | null;
  /** Hepatic extraction ratio, for oral first-pass. */
  hepaticExtraction: number | null;
  /** Michaelis-Menten parameters for saturable metabolism (ethanol, phenytoin). */
  vmax_mg_per_min: number | null;
  km_mg_per_L: number | null;
  provenance: Record<string, Provenance>;
}

export interface DrugTarget {
  receptorId: string;
  Ki_nM: number | null;
  /**
   * WHAT THIS MEANS DEPENDS ON THE TARGET'S `activationModel`. See ADR-025; reading
   * one number three ways without saying so is what inverted carvedilol, amfetamine,
   * milrinone and every NSAID at once.
   *
   *  - `endogenous-agonist`: EFFICACY relative to the endogenous agonist. 1 full
   *    agonist, 0 neutral antagonist, <0 inverse agonist. A fraction here is only
   *    meaningful because there is an endogenous ligand to be a fraction OF.
   *  - `inhibition` (enzyme, ion channel): a DIRECTION, not an efficacy. <=0 means
   *    inhibitor/blocker and drives the receptor's effect vector as written; >0 means
   *    activator/opener and drives it backwards.
   *  - `transporter`: a DIRECTION. <0 reuptake inhibition, >0 substrate/releaser;
   *    both raise synaptic transmitter, which is what the effect vector describes.
   */
  intrinsicActivity: number;
  /** Association rate, 1/(nM*min). Null means "derive from Ki and the default kon". */
  kon: number | null;
  koff: number | null;
  source: string;
  sourceUrl: string;
  confidence: 'measured' | 'derived' | 'assumed';
}

export interface DirectEffect {
  target: string;
  gain: number;
  note: string;
  source: string;
  sourceUrl: string;
}


/**
 * Pulse's pharmacodynamic block (spec 5.6). Its Emax form is the same as ours:
 *
 *   effect = modifier * C^n / (EC50^n + C^n)
 *
 * so the values drop almost directly into the engine. This is how a drug whose
 * receptor affinities GtoPdb does not publish — propofol and midazolam at GABA-A,
 * for instance — still produces a real, cited, concentration-dependent response
 * instead of nothing. The modifiers are fractional changes from baseline.
 */
export interface PulsePd {
  /** Concentration for half-maximal effect, ug/mL (== mg/L), as Pulse reports it. */
  ec50_mg_per_L: number;
  /** Hill slope, Pulse's EMaxShapeParameter. */
  emaxShape: number;
  modifiers: {
    heartRate?: number;
    systolicPressure?: number;
    diastolicPressure?: number;
    respirationRate?: number;
    tidalVolume?: number;
    sedation?: number;
    bronchodilation?: number;
    neuromuscularBlock?: number;
    tubularPermeability?: number;
  };
  /**
   * The receptor this whole concentration-effect block is mediated by, when the drug's
   * pharmacology names one, or null when it does not.
   *
   * A Pulse block is a whole-drug curve fitted to an exposure, not a binding assay, so
   * by default it runs in parallel to receptor occupancy and nothing at a receptor can
   * touch it. That is why flumazenil could not reverse midazolam: midazolam has no
   * published human GABA-A affinity at all, its entire effect runs through this block,
   * and an antagonist saturating the benzodiazepine site had nowhere to bite.
   *
   * Naming the site makes the block COMPETABLE without inventing a Ki for the drug that
   * owns it: see `applyPulsePd` in sim/pharma/pulsepd.ts. ADR-026.
   */
  mediatedBy: string | null;
  source: string;
  sourceUrl: string;
}

/** Absorption figures for one drug by one route, from that product's own label. */
export interface RoutePk {
  ka_min?: number;
  bioavailability?: number;
  lagMin?: number;
  provenance: Provenance;
}

export interface Drug {
  id: string;
  displayName: string;
  class: DrugClass;
  /** Heading this drug appears under in the drawer, declared in the manifest. */
  drawerGroup: string;
  /** A controlled or recreational substance; the interface says so plainly. */
  scheduled?: boolean;
  /** Why it is modelled. Present whenever `scheduled` is. */
  scheduleNote?: string;
  routes: Route[];
  presetDoses: PresetDose[];
  pk: PkParams;
  targets: DrugTarget[];
  directEffects: DirectEffect[];
  /** Concentration-effect block taken from the Pulse substance table, when it has one. */
  pulsePd: PulsePd | null;
  /**
   * Per-route absorption figures published for a REAL PRODUCT, which override the
   * generic route defaults in src/data/routes.json. A naloxone nasal spray and a
   * fentanyl patch are licensed products with their own measured kinetics, and those
   * beat any ratio scaled off the intramuscular route.
   */
  routePk?: Partial<Record<Route, RoutePk>>;
  /** Electrolyte/fluid payload delivered directly to the blood compartment. */
  payload?: {
    volume_mL?: number;
    na_mEq?: number;
    k_mEq?: number;
    ca_mmol?: number;
    cl_mEq?: number;
    iron_mg?: number;
    /** Grams of glucose per preset unit: dextrose. Lands in the Bergman glucose pool. */
    glucose_g?: number;
    /** mEq of bicarbonate per preset unit: sodium bicarbonate. Lands in the buffer. */
    hco3_mEq?: number;
  };
  /**
   * A DRUG THAT IS A HORMONE.
   *
   * Insulin, hydrocortisone, glucagon, vasopressin and levothyroxine are the body's own
   * molecules given from outside. Modelling them through a receptor alone would give the
   * body two insulins that never meet - the injected one acting at `insulin_r` and the
   * secreted one in the Bergman model - so a hypoglycaemic patient's own counter-
   * regulation could never see the dose. Instead the drug's plasma concentration is
   * converted into the hormone's own clinical unit and ADDED to the endogenous pool, and
   * everything downstream (feedback, effects, the lab panel) sees one number.
   *
   * `unitsPerMgPerL` converts plasma concentration in mg/L into the pool's unit
   * (uU/mL for insulin, ug/dL for cortisol, pg/mL for glucagon and ADH, ng/dL for free
   * T4). It is arithmetic on a cited molar or unit definition, never a fitted number.
   */
  hormoneAnalogue?: {
    pool: 'insulin' | 'cortisol' | 'glucagon' | 'adh' | 'thyroxine' | 'epo';
    unitsPerMgPerL: number;
    note: string;
    source: string;
    sourceUrl: string;
  };
  /**
   * WHAT A DRUG DOES TO A PATHOGEN.
   *
   * Kill (or, for a virustatic drug, suppressed replication) follows an Emax model on
   * the FREE plasma concentration with the MIC (or antiviral EC50) as the potency term -
   * the standard pharmacokinetic-pharmacodynamic form for antimicrobials (Nielsen &
   * Friberg, Pharmacol Rev 2013). Only pathogens listed in `spectrum` are affected, so
   * an antibiotic given for influenza visibly does nothing, which is the lesson.
   */
  antimicrobial?: {
    spectrum: { pathogenId: string; mic_mg_per_L: number; source: string; sourceUrl: string; note?: string }[];
    /** Maximal kill rate at saturating concentration, per hour. */
    maxKill_per_h: number;
    /** Hill slope of the concentration-kill curve. */
    hill: number;
    /** Which exposure index predicts efficacy, for the explanation text. */
    pattern: 'time-dependent' | 'concentration-dependent' | 'exposure-dependent';
    killSource: string;
    killSourceUrl: string;
    note: string;
  };
  notes: string;
  sources: string[];
}

export interface DrugsFile {
  version: number;
  generatedBy: string;
  generatedAt: string;
  attribution: string[];
  drugs: Drug[];
}

/* ------------------------------------------------------------------ receptors */

export interface ReceptorEffect {
  target: string;
  gain: number;
  source: string;
  sourceUrl: string;
  note?: string;
}

/**
 * HOW OCCUPANCY BECOMES ACTIVATION AT THIS TARGET (ADR-025).
 *
 * The registry holds three quite different kinds of thing under one word. Which one a
 * target is decides what its `effects[].gain` values are written RELATIVE TO, and
 * therefore what `intrinsicActivity` can possibly mean there.
 *
 *  - `endogenous-agonist` — a receptor with an endogenous ligand whose tone the model
 *    tracks in `baselineTone`. The effect vector is written for the ACTIVATED state,
 *    and a drug acts by changing activation away from that resting tone. This is the
 *    only model in which an efficacy fraction means anything.
 *
 *  - `inhibition` — a constitutively active ENZYME or an ion CHANNEL. There is no
 *    agonist, endogenous or otherwise; every drug in the set that touches one is an
 *    inhibitor or a blocker, and the effect vector is written for the INHIBITED state.
 *    Response therefore follows drug occupancy directly. `baselineTone` for these is a
 *    statement that the target is active at rest — which is what lets an inhibitor work
 *    with no agonist present — and NOT a term in the response, because the effect
 *    vector is already written relative to that resting activity.
 *
 *  - `transporter` — the readout is synaptic transmitter concentration, and the effect
 *    vector is written for "transmitter raised". A reuptake inhibitor raises it by
 *    blocking clearance and a substrate/releaser raises it by running the carrier
 *    backwards, so BOTH signs of `intrinsicActivity` drive the vector the same way.
 *    `baselineTone` is zero for these: nothing blocks a transporter at rest.
 */
export type ReceptorActivationModel = 'endogenous-agonist' | 'inhibition' | 'transporter';

export interface Receptor {
  id: string;
  label: string;
  /** Display grouping and pill colour family in the receptor panel. */
  group: 'adrenergic' | 'cholinergic' | 'dopaminergic' | 'serotonergic' | 'histaminergic'
       | 'opioid' | 'amino-acid' | 'transporter' | 'peptide' | 'cannabinoid' | 'metabolic' | 'trace-amine'
       // Added for the wider therapeutic set. An enzyme and an ion channel are not
       // receptors, but the binding model — occupancy from free concentration and an
       // affinity — describes a reversible inhibitor just as well, and GtoPdb lists
       // them in the same table. What differs is the sign convention: for these the
       // "agonist" is the inhibitor.
       | 'enzyme' | 'channel' | 'nuclear' | 'purinergic';
  /** Which tissues express it, for the organ-panel filter. */
  tissues: string[];
  /** How occupancy becomes activation here, and therefore what the gains mean. */
  activationModel: ReceptorActivationModel;
  /**
   * Resting endogenous occupancy, 0..1. An antagonist displaces this.
   *
   * Load-bearing ONLY under `activationModel: 'endogenous-agonist'`. Under
   * `'inhibition'` it is the descriptive claim that the target is constitutively
   * active; under `'transporter'` it is zero by definition. See ADR-025.
   */
  baselineTone: number;
  /** What drives baselineTone dynamically, if anything. */
  endogenousDriver: 'sympathetic' | 'parasympathetic' | 'none';
  /**
   * How much of this receptor's modelled effect sits behind the blood-brain
   * barrier, 0..1. A drug that cannot cross reaches only the peripheral share.
   * This is what stops circulating adrenaline producing central sympatholysis
   * through alpha-2, which it does not do and which would cancel its own pressor
   * effect if modelled naively.
   */
  centralFraction: number;
  /** Occupancy at half-maximal downstream effect, 0..1. See receptor reserve. */
  ec50Occupancy: number;
  /** Hill coefficient of the occupancy-to-effect transform. */
  hill: number;
  effects: ReceptorEffect[];
  gtopdbTargetId: number | null;
  notes: string;
}

export interface ReceptorsFile {
  version: number;
  generatedBy: string;
  generatedAt: string;
  attribution: string[];
  /** Default association rate used when a target has a Ki but no measured kon. */
  defaultKon: { value: number; unit: string; source: string; sourceUrl: string; confidence: string; note: string };
  receptors: Receptor[];
}
